marks = [67,98.2,66,96,56]
print(marks[0])
print(len(marks))
print(marks[2:4])
print(marks[:4])
print(marks[2:])
print(marks[1:len(marks)])
print(marks[-4:])
marks.append(87)
marks.sort()
print(marks)
marks.sort(reverse=True)
marks.insert(4,35)
print(marks)
list = ["apple", "az", "apple", 'cat', "ball"]
list.sort()
print(list)
list.remove("apple")
list.pop(1)
print(list)